Traceback (most recent call last):
  File "traceback_file.py", line 4, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
